# Generated by Django 4.2.30 on 2026-05-02 00:50

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Igreja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome da Igreja')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('paroquia', models.BooleanField(default=False, verbose_name='Paróquia')),
                ('capela', models.BooleanField(default=False, verbose_name='Capela')),
                ('aberta_ao_publico', models.BooleanField(default=True, verbose_name='Aberta ao Público')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('sacerdotes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sacerdotes')),
                ('telefone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefones')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='igrejas/', verbose_name='Imagem')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('site', models.URLField(blank=True, null=True, verbose_name='Site')),
                ('facebook', models.URLField(blank=True, max_length=100, null=True, verbose_name='Facebook')),
                ('instagram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='YouTube')),
                ('maps', models.URLField(blank=True, null=True, verbose_name='Google Maps')),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, unique=True, verbose_name='Slug')),
                ('contato_whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contato WhatsApp')),
            ],
            options={
                'verbose_name': 'Igreja',
                'verbose_name_plural': 'Igrejas',
            },
        ),
        migrations.CreateModel(
            name='TipoCelebracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('categoria', models.CharField(choices=[('missa', 'Missa'), ('celebracao', 'Celebração da Palavra'), ('adoracao', 'Adoração ao Santíssimo'), ('batismo', 'Batismo'), ('casamento', 'Casamento'), ('confissao', 'Confissão'), ('outros', 'Outros')], max_length=20, verbose_name='Categoria')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('dia', models.CharField(choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=20, verbose_name='Dia da Semana')),
                ('exige_agendamento', models.BooleanField(default=False, verbose_name='Exige Agendamento')),
                ('exibir_no_site', models.BooleanField(default=True, verbose_name='Exibir no Site')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_celebracao', to='igreja.igreja')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
