# Generated by Django 4.2.30 on 2026-05-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igreja', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipocelebracao',
            options={'verbose_name': 'Tipo de Celebração', 'verbose_name_plural': 'Tipos de Celebração'},
        ),
        migrations.AddField(
            model_name='tipocelebracao',
            name='horario_fim',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de Término'),
        ),
        migrations.AddField(
            model_name='tipocelebracao',
            name='horario_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de Início'),
        ),
    ]
