# Generated by Django 4.2.30 on 2026-05-03 16:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igreja', '0002_alter_tipocelebracao_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocelebracao',
            name='dia_mes',
            field=models.PositiveIntegerField(blank=True, help_text='Use este campo para celebrações mensais. Exemplo: dia 13 de cada mês.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dia do Mês'),
        ),
        migrations.AddField(
            model_name='tipocelebracao',
            name='recorrencia',
            field=models.CharField(choices=[('semanal', 'Semanal'), ('mensal_dia_fixo', 'Mensal em dia fixo')], default='semanal', max_length=20, verbose_name='Recorrência'),
        ),
        migrations.AlterField(
            model_name='igreja',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='igreja',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='tipocelebracao',
            name='categoria',
            field=models.CharField(choices=[('missa', 'Santa Missa'), ('missa_votiva', 'Missa Votiva'), ('celebracao', 'Celebração da Palavra'), ('adoracao', 'Adoração ao Santíssimo'), ('batismo', 'Batismo'), ('casamento', 'Casamento'), ('confissao', 'Confissão'), ('outros', 'Outros')], max_length=20, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='tipocelebracao',
            name='dia',
            field=models.CharField(blank=True, choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=20, null=True, verbose_name='Dia da Semana'),
        ),
    ]
