# Generated by Django 4.2.30 on 2026-05-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igreja', '0003_tipocelebracao_dia_mes_tipocelebracao_recorrencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocelebracao',
            name='data_especifica',
            field=models.DateField(blank=True, help_text='Use para celebrações extraordinárias, como casamento ou missa de corpo presente.', null=True, verbose_name='Data Específica'),
        ),
        migrations.AlterField(
            model_name='tipocelebracao',
            name='recorrencia',
            field=models.CharField(choices=[('semanal', 'Semanal'), ('mensal_dia_fixo', 'Mensal em dia fixo'), ('data_especifica', 'Data específica')], default='semanal', max_length=20, verbose_name='Recorrência'),
        ),
    ]
