# Generated by Django 4.2.30 on 2026-05-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igreja', '0004_tipocelebracao_data_especifica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('mensagem', models.TextField(blank=True, null=True, verbose_name='Mensagem')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('ip_contato', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Aceite')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
    ]
