# Generated by Django 4.2.30 on 2026-05-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igreja', '0005_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocelebracao',
            name='categoria',
            field=models.CharField(choices=[('missa', 'Santa Missa'), ('missa_votiva', 'Missa Votiva'), ('missa_corpo_presente', 'Missa de Corpo Presente'), ('celebracao', 'Celebração da Palavra'), ('adoracao', 'Adoração ao Santíssimo'), ('batismo', 'Batismo'), ('casamento', 'Casamento'), ('confissao', 'Confissão'), ('outros', 'Outros')], max_length=30, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='tipocelebracao',
            name='recorrencia',
            field=models.CharField(choices=[('semanal', 'Semanal'), ('mensal_dia_fixo', 'Mensal em dia fixo'), ('data_especifica', 'Data específica')], default='semanal', max_length=30, verbose_name='Recorrência'),
        ),
    ]
