# Generated by Django 4.2.30 on 2026-05-04 00:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('igreja', '0006_alter_tipocelebracao_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='igreja',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=150, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
