# Generated by Django 4.2.30 on 2026-05-08 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igreja', '0007_contato_uuid_alter_igreja_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocelebracao',
            name='semana_do_mes',
            field=models.IntegerField(blank=True, choices=[(1, 'Primeiro'), (2, 'Segundo'), (3, 'Terceiro'), (4, 'Quarto'), (5, 'Quinto'), (-1, 'Último')], help_text='Use para celebrações mensais por dia da semana. Exemplo: primeira segunda-feira do mês.', null=True, verbose_name='Semana do Mês'),
        ),
        migrations.AlterField(
            model_name='tipocelebracao',
            name='recorrencia',
            field=models.CharField(choices=[('semanal', 'Semanal'), ('mensal_dia_fixo', 'Mensal em dia fixo'), ('mensal_dia_semana', 'Mensal por dia da semana'), ('data_especifica', 'Data específica')], default='semanal', max_length=30, verbose_name='Recorrência'),
        ),
    ]
