# Generated by Django 4.2.30 on 2026-05-08 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igreja', '0008_tipocelebracao_semana_do_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='igreja',
            name='contato_whatsapp',
            field=models.CharField(blank=True, help_text='Escreva o DDD e o telefone tudo junto, sem espaços ou caracteres. Exemplo: 86912345678', max_length=20, null=True, verbose_name='Contato WhatsApp'),
        ),
        migrations.AlterField(
            model_name='igreja',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='igreja',
            name='facebook',
            field=models.URLField(blank=True, help_text='Informe apenas Link do Perfil.', max_length=100, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='igreja',
            name='instagram',
            field=models.CharField(blank=True, help_text='Informe apenas o nome de usuário, sem @ ou URL. Exemplo: paroquia_fatima', max_length=100, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='igreja',
            name='maps',
            field=models.URLField(blank=True, help_text='Cole aqui o link do Google Maps para a localização da igreja. Exemplo: https://www.google.com/maps/place/Igreja+Exemplo/@-5.123456,-42.123456,17z', null=True, verbose_name='Google Maps'),
        ),
        migrations.AlterField(
            model_name='igreja',
            name='site',
            field=models.URLField(blank=True, help_text='Informe apenas o Link do Site.', max_length=100, null=True, verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='igreja',
            name='youtube',
            field=models.URLField(blank=True, help_text='Informe apenas o Link do Canal.', null=True, verbose_name='YouTube'),
        ),
    ]
